# This is a basic workflow to help you get started with Actions

name: Print workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  print_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print hello
        run: echo "Hello world!"

    
      
