# This is a basic workflow to help you get started with Actions

name: Print workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  print_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print hello
        run: echo "Hello world!"

  print_full_technical_info:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print full_tech_info
        run: sudo lshw

  print_short_technical_info:
    runs-on: ubuntu-latest

    steps:
      - name: Print short_technical_info
        run:  sudo lshw -short
  
    
      
